# Generated by Django 4.2.6 on 2023-10-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_alter_expense_expense_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
