# Generated by Django 4.2.6 on 2023-10-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_rename_customer_id_expense_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='password', max_length=250),
            preserve_default=False,
        ),
    ]
